### PR TITLE
Update DoDonPachi (20120212 Arrange Ver. 1.1).mad

### PR DESCRIPTION
**Pull request by Abadede**

### CODE REVIEW

**Comment by misteraddons** [comment]
I can't change the setname if I want to use merged roms

I'm using the <parent> tag to track parent game, not parent rom set

Regarding the year, I can change it but it feels out of place to say it's from 2012 since it's a hack.

**Comment by misteraddons** [comment]
Actually, I'm using <parent> to link alternative mra files to their parent title. Kind of convoluted haha

**Comment by Abadede** [comment]
Got it. IIRC having wrong `<parent_title>` was preventing parent mra to appear in __Organized_ folders though.

**Comment by misteraddons** [comment]
I don't see any compelling changes with the pull request. Most of these tags are generated from a spreadsheet.

**Pull request closed without merging**
